#!/bin/sh

MOUNT_NAME=$1
CREDENTIAL_ID=$2

echo
echo Databricks S3 Mount Utility
echo 
echo This tool will create an AWS role and policy to enable Databricks to securely 
echo access an S3 storage bucket as a Unity Catalog external location.
echo

read -p "Enter the name of the AWS storage bucket to mount: " STORAGE_BUCKET

ACCOUNT_ID=$(aws sts get-caller-identity \
    --output text --query 'Account')

echo Creating role ${MOUNT_NAME}role...
CREATE_ROLE_RESULT=$(aws iam create-role \
    --output text --query 'Role.RoleId' \
    --role-name ${MOUNT_NAME}role \
    --assume-role-policy-document '{
        "Version": "2012-10-17",
        "Statement": [ {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL"
                ]
            },
            "Action": "sts:AssumeRole",
            "Condition": {
                "StringEquals": {
                    "sts:ExternalId": "'${CREDENTIAL_ID}'"
                }
            }
        } ]
    }') 

echo Creating policy ${MOUNT_NAME}policy...
CREATE_POLICY_RESULT=$(aws iam create-policy \
    --output text --query 'Policy.PolicyId' \
    --policy-name ${MOUNT_NAME}policy \
    --policy-document '{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::'${STORAGE_BUCKET}'/*",
                "arn:aws:s3:::'${STORAGE_BUCKET}'"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "sts:AssumeRole"
            ],
            "Resource": [
                "arn:aws:iam:::role/'${MOUNT_NAME}'role"
            ],
            "Effect": "Allow"
        }
        ]
    }')

echo Attaching policy to role...
CREATE_ATTACH_ROLE_POLICY_RESULT=$(aws iam attach-role-policy \
    --role-name ${MOUNT_NAME}role \
    --policy-arn arn:aws:iam::${ACCOUNT_ID}:policy/${MOUNT_NAME}policy)

sleep 3

echo Updating assume role policy...
UPDATE_ASSUME_ROLE_POLICY_RESULT=$(aws iam update-assume-role-policy \
    --role-name ${MOUNT_NAME}role \
    --policy-document '{
        "Version": "2012-10-17",
        "Statement": [ {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL",
                     "arn:aws:iam::'${ACCOUNT_ID}':role/'${MOUNT_NAME}'role"
                ]
            },
            "Action": "sts:AssumeRole",
            "Condition": {
                "StringEquals": {
                    "sts:ExternalId": "'${CREDENTIAL_ID}'"
                }
            }
        } ]
    }')

echo Created AWS role and policy successfully.
echo
echo Return to Databricks, and enter the following to finish mounting the storage location:
echo
echo URL: s3://${STORAGE_BUCKET}
echo IAM Role (ARN): arn:aws:iam::${ACCOUNT_ID}:role/${MOUNT_NAME}role
echo